/*
 * This source file was generated by the Gradle 'init' task
 */
package proyecto_estructuras;

/**
 * Clase wrapper generada por Gradle que actúa como punto de entrada del build
 * system.
 * <p>
 * Delega la ejecución al método {@link Main#main(String[])} que inicializa
 * la interfaz gráfica del sistema.
 * </p>
 *
 * @see Main
 */
public class App {

    /**
     * Punto de entrada definido en {@code build.gradle}.
     * Delega a {@link Main#main(String[])}.
     *
     * @param args argumentos de línea de comandos
     */
    public static void main(String[] args) {
        Main.main(args);
    }
}
